//caminho padrão para imagens

:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

= List View

A List View é um grupo de views cujo objetivo é apresentar itens no sentido vertical, ou seja um embaixo do outro. Cada item é uma view. As listas podem ser simples e personalizadas. O componente ListView não consegue acessar os dados a serem mostrados diretamente. Para esse propósito, é necessário usar um Adapter. Dessa forma, é usado um ListAdapter, que implementa as funcionalidades da interface Adapter, esta classe tem acesso direto aos dados a serem visualizados. Se for usado uma lista simples, basta usar a estrutura pronta que o Android fornece, mas na lista personalizada é necessário usar um Adaptar específico para dar suporte aos dados que serão mostrados.

ListView é conteiner responsável em exibir as views.
Adapter tem a função de criar e fornecer as views que são mostradas no ListView. Existem algumas variações:

- ArrayAdapter: Adapter simples que usa uma lista de objetos (ArrayList) para criar views.
- CursorAdapter: Adapter que pode ser usado com dados retornados de um banco de dados.
- BaseAdapter: Adapter que permite criar adaptadores personalizados para criar views personalizadas.

Para mais detalhes sobre este componente veja: GOOGLE DEVELOPERS. ListView. Disponível em:  https://developer.android.com/reference/android/widget/ListView. Acesso em: 23 ago.2024.
      
Exemplos práticos (lista simples)

- string.xml
[source,xml]
<resources>
    <string name="app_name">ExemploListaSimples</string>
    <string-array name="c">
        <item>C é uma linguagem que usa o paradigma estruturado</item>
        <item>C tem uma sintaxe simples</item>
        <item>C é muito eficiente em termos de performance</item>
    </string-array>
    <string-array name="java">
        <item>JAVA é orientada a objetos</item>
        <item>JAVA é multiplataforma</item>
        <item>JAVA é amplamente usada no desenvolvimento Android</item>
    </string-array>
    <string-array name="kotlin">
        <item>Kotlin é 100% interoperável com Java</item>
        <item>Kotlin é concisa e expressiva</item>
        <item>Kotlin é usado como linguagem oficial para Android</item>
    </string-array>
    <string-array name="lua">
        <item>LUA é uma linguagem embutida</item>
        <item>LUA tem uma sintaxe simples e fácil de aprender</item>
        <item>LUA é muito usada em jogos e sistemas embarcados</item>
    </string-array>
    <string-array name="pascal">
        <item>PASCAL é uma linguagem estruturada</item>
        <item>PASCAL é usada no ensino de programação</item>
        <item>PASCAL é forte em tipagem e fácil de entender</item>
    </string-array>
    <string-array name="python">
        <item>Python tem uma sintaxe simples e legível</item>
        <item>Python é amplamente usada em ciência de dados</item>
        <item>Python tem uma grande comunidade de desenvolvedores</item>
    </string-array>
</resources>

- activity_main.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:padding="16dp">
    <ListView
        android:id="@+id/listaLinguagens"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
</LinearLayout>

- Linguagem.java
[source,java]
import java.util.ArrayList;
public class Linguagem {
    private ArrayList<String> listaLinguagens;
    public Linguagem() {
        listaLinguagens = new ArrayList<>();
        preencherLista();
    }
    private void preencherLista() {
        listaLinguagens.add("C");
        listaLinguagens.add("JAVA");
        listaLinguagens.add("KOTLIN");
        listaLinguagens.add("LUA");
        listaLinguagens.add("PASCAL");
        listaLinguagens.add("PYTHON");
    }
    public ArrayList<String> getListaLinguagens() {
        return listaLinguagens;
    }
    public String getLinguagem(int position) {
        return listaLinguagens.get(position);
    }
}

- MainActivity.java
[source,java]
import androidx.appcompat.app.AppCompatActivity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;
import java.util.ArrayList;
public class MainActivity extends AppCompatActivity implements AdapterView.OnItemClickListener, AdapterView.OnItemLongClickListener {
    private ListView listViewLinguagens;
    private Linguagem linguagem;
    private ArrayAdapter<String> adapter;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        listViewLinguagens = findViewById(R.id.listaLinguagens);
        linguagem = new Linguagem();
        preencherAdapter();
        listViewLinguagens.setAdapter(adapter);
        listViewLinguagens.setOnItemClickListener(this);
        listViewLinguagens.setOnItemLongClickListener(this);
    }
    private void preencherAdapter() {
        ArrayList<String> listaLinguagens = linguagem.getListaLinguagens();
        adapter = new ArrayAdapter<>(getApplicationContext(),
                android.R.layout.simple_list_item_1, listaLinguagens);
    }
    @Override
    public void onItemClick(AdapterView<?> adapterView, View view, int i, long l) {
        String item = adapterView.getItemAtPosition(i).toString();
        abrirTela(item);  
    }
    public void abrirTela(String item) {
        Intent intent;
        switch (item) {
            case "C":
                intent = new Intent(MainActivity.this,
                        Activity2.class);
                intent.putExtra("linguagem", "C");
                startActivity(intent);
                break;
            case "JAVA":
                intent = new Intent(MainActivity.this,
                        Activity2.class);
                intent.putExtra("linguagem", "JAVA");
                startActivity(intent);
                break;
            //adicionar os outros case
            default:
                Toast.makeText(this, "opção inválida", Toast.LENGTH_SHORT).show();
                break;
        }
    }
    @Override
    public boolean onItemLongClick(AdapterView<?> adapterView, View view, int i, long l) {
        String linguagem = adapterView.getItemAtPosition(i).toString();
        Toast.makeText(this, linguagem, Toast.LENGTH_SHORT).show();
        return true;
    }
}

- activity_2.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:padding="10dp">
    <TextView
        android:id="@+id/textViewCaracteristicas"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Características"
        android:textAppearance="@style/TextAppearance.AppCompat.Medium"/>
</LinearLayout>

- Activity2.java
[source,java]
import android.content.Intent;
import android.os.Bundle;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;
import java.util.HashMap;
import java.util.Map;
public class Activity2 extends AppCompatActivity {
    private static final Map<String, Integer> linguagemParaCaracteristicas
            = new HashMap<>();
    static {
        linguagemParaCaracteristicas.put("C", R.array.c);
        linguagemParaCaracteristicas.put("JAVA", R.array.java);
        linguagemParaCaracteristicas.put("KOTLIN", R.array.kotlin);
        linguagemParaCaracteristicas.put("LUA", R.array.lua);
        linguagemParaCaracteristicas.put("PASCAL", R.array.pascal);
        linguagemParaCaracteristicas.put("PYTHON", R.array.python);
    }
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_2);
        Intent intent = getIntent();
        String linguagemSelecionada = intent.getStringExtra("linguagem");
        Integer arrayResId = linguagemParaCaracteristicas.get(linguagemSelecionada.toUpperCase());
        if (arrayResId != null) {
            String[] caracteristicas = getResources().getStringArray(arrayResId);
            TextView textViewCaracteristicas = findViewById(R.id.textViewCaracteristicas);
            StringBuilder caracteristicasTexto = new StringBuilder();
            for (String caracteristica : caracteristicas) {
                caracteristicasTexto.append(caracteristica).append("\n");
            }
            textViewCaracteristicas.setText(caracteristicasTexto.toString());
        } else {
            TextView textViewCaracteristicas = findViewById(R.id.textViewCaracteristicas);
            textViewCaracteristicas.setText("Características não disponíveis para essa linguagem.");
        }
    }
}

Exemplos práticos (lista personalizada)

- colors.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="black">#FF000000</color>
    <color name="white">#FFFFFFFF</color>
    <color name="red">#DC3737</color>
</resources>

- item_lista.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="horizontal"
    android:padding="10dp"
    >
    <ImageView
        android:id="@+id/imagem"
        android:layout_width="60dp"
        android:layout_height="60dp"
        android:src="@mipmap/ic_launcher"
        />
    <TextView
        android:id="@+id/texto"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:gravity="center_vertical"
        android:textColor="@color/black"
        android:textAppearance="@style/TextAppearance.AppCompat.Medium" />
</LinearLayout>

- activity_main.xml
[source,xml]
<?xml version="1.0" encoding="UTF-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:padding="10dp"
    >
    <ListView
        android:id="@+id/lista"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:divider="@color/red"
        android:dividerHeight="1dp"
       />
</LinearLayout>

- ItemLista.java
[source,java]
public class ItemLista {
    private String nome;
    private int imagem;
    public ItemLista(String nome, int imagem) {
        this.nome = nome;
        this.imagem = imagem;
    }
    public String getNome() {
        return nome;
    }
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getImagem() {
        return imagem;
    }
    public void setImagem(int imagem) {
        this.imagem = imagem;
    }
}

- RepositorioItens.java
[source,java]
import java.util.ArrayList;
import java.util.List;
public class RepositorioItens {
    public List<ItemLista> obterItens() {
        List<ItemLista> itens = new ArrayList<>();
        itens.add(new ItemLista("item 1", R.drawable.ic_launcher_foreground));
        itens.add(new ItemLista("item 2", R.drawable.ic_launcher_foreground));
        itens.add(new ItemLista("item 3", R.drawable.ic_launcher_foreground));
        return itens;
    }
}

- MeuAdapter.java
[source,java]
import android.content.Context;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.BaseAdapter;
import android.widget.ImageView;
import android.widget.TextView;
import java.util.List;
public class MeuAdapter extends BaseAdapter {
    private LayoutInflater inflater;
    private List<ItemLista> itens;
    public MeuAdapter(Context context, List<ItemLista> itens) {
        this.itens = itens;
        this.inflater = LayoutInflater.from(context);
    }
    @Override
    public int getCount() {
        return itens.size();
    }
    @Override
    public ItemLista getItem(int position) {
        return itens.get(position);
    }
    @Override
    public long getItemId(int position) {
        return position;
    }
    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        if (convertView == null) {
            convertView = inflater.inflate(R.layout.item_lista, parent, false);
        }
        ItemLista item = getItem(position);
        TextView texto = convertView.findViewById(R.id.texto);
        texto.setText(item.getNome());
        ImageView imagem = convertView.findViewById(R.id.imagem);
        imagem.setImageResource(item.getImagem());
        return convertView;
    }
}

- MainActivity.java
[source,java]
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;
import java.util.List;
public class MainActivity extends AppCompatActivity implements AdapterView.OnItemClickListener {
    private ListView listView;
    private MeuAdapter meuAdapter;
    private RepositorioItens repositorioItens;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        listView = findViewById(R.id.lista);
        listView.setOnItemClickListener(this);
        repositorioItens = new RepositorioItens();
        List<ItemLista> itens = repositorioItens.obterItens();
        meuAdapter = new MeuAdapter(this, itens);
        listView.setAdapter(meuAdapter);
    }
    @Override
    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        ItemLista item = (ItemLista) parent.getItemAtPosition(position);
        Toast.makeText(this, "Você Clicou em: " + item.getNome(), Toast.LENGTH_LONG).show();
    }
}






