= Biblioteca ROOM

O SDK do Android fornece uma biblioteca que facilita o uso do banco de dados. Conforme consta na documentação oficial, a biblioteca ROOM adiciona uma camada de abstração retirando as implementações mais complexas do banco SQLite. Para mais detalhes, acesse a página: GOOGLE DEVELOPERS. Salvar dados em um banco de dados local usando Room. Disponível em: https://developer.android.com/training/data-storage/room?hl=pt-br. Acessado em 20 ago. 2025.

Para usar a lib ROOM no seu projeto, primeiramente é necessário importar a biblioteca. Dessa forma, deve-se ir no arquivo Gradle a nível de app e adicionar as duas linhas no bloco de dependências:

[source,xml]
implementation ("androidx.room:room-runtime:2.4.0")
annotationProcessor ("androidx.room:room-compiler:2.4.0")

ou

[source,xml]
implementation("androidx.room:room-runtime:2.7.0-rc03")
annotationProcessor("androidx.room:room-compiler:2.7.0-rc03")

Exemplos práticos:

Versão 1:

- activity_main.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:padding="10dp"
    android:orientation="vertical"
    tools:context=".MainActivity">
    <EditText
        android:id="@+id/editTextNome"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="20dp"
        android:hint="Digite seu nome" />
    <EditText
        android:id="@+id/editTextTelefone"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:hint="Digite seu telefone" />
    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        android:layout_marginTop="20dp">
        <Button
            android:id="@+id/buttonS"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginEnd="5dp"
            android:layout_weight="1"
            android:onClick="clicar"
            android:text="Salvar" />
        <Button
            android:id="@+id/buttonL"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginEnd="5dp"
            android:layout_weight="1"
            android:onClick="clicar"
            android:text="Listar" />
        <Button
            android:id="@+id/buttonD"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_weight="1"
            android:onClick="clicar"
            android:text="Excluir" />
    </LinearLayout>
</LinearLayout>

- activity_segunda.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".SegundaActivity">
    <ListView
        android:id="@+id/lista"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />
</LinearLayout>

- Pessoa.java
[source,java]
import android.os.Parcel;
import android.os.Parcelable;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;
@Entity
public class Pessoa implements Parcelable {
    @PrimaryKey(autoGenerate = true)
    private int id;
    @ColumnInfo(name = "nome")
    private String nome;
    @ColumnInfo(name = "telefone")
    private String telefone;
    public Pessoa(int id, String nome, String telefone) {
        this.id = id;
        this.nome = nome;
        this.telefone = telefone;
    }
    public Pessoa() {}
    protected Pessoa(Parcel in) {
        id = in.readInt();
        nome = in.readString();
        telefone = in.readString();
    }
    public static final Creator<Pessoa> CREATOR = new Creator<Pessoa>() {
        @Override
        public Pessoa createFromParcel(Parcel in) {
            return new Pessoa(in);
        }
        @Override
        public Pessoa[] newArray(int size) {
            return new Pessoa[size];
        }
    };
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }
    public String getNome() { return nome; }
    public void setNome(String nome) { this.nome = nome; }
    public String getTelefone() { return telefone; }
    public void setTelefone(String telefone) { this.telefone = telefone; }
    @Override
    public String toString() {
        return nome + " - " + telefone;
    }
    @Override
    public int describeContents() {
        return 0;
    }
    @Override
    public void writeToParcel(Parcel parcel, int flags) {
        parcel.writeInt(id);
        parcel.writeString(nome);
        parcel.writeString(telefone);
    }
}

- Banco.java
[source,java]
import androidx.room.Database;
import androidx.room.RoomDatabase;
@Database(entities = {Pessoa.class}, version = 1)
public abstract class Banco extends RoomDatabase {
    public abstract PessoaDao pessoaDao();
}

- PessoaDao.java
[source,java]
import androidx.room.Dao;
import androidx.room.Delete;
import androidx.room.Insert;
import androidx.room.Query;
import androidx.room.Update;
import java.util.List;
@Dao
public interface PessoaDao {
    @Insert
    long adicionar(Pessoa p);
    @Query("SELECT * FROM pessoa")
    List<Pessoa> listar();
    @Update
    int atualizar(Pessoa p);
    @Delete
    int excluir(Pessoa p);
}

- MainActivity.java
[source,java]
import androidx.appcompat.app.AppCompatActivity;
import androidx.room.Room;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;
import java.util.ArrayList;
public class MainActivity extends AppCompatActivity {
    private EditText editTextNome, editTextTelefone;
    private Button buttonS, buttonD, buttonL;
    private Pessoa p;
    private PessoaDao dao;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        editTextNome = findViewById(R.id.editTextNome);
        editTextTelefone = findViewById(R.id.editTextTelefone);
        buttonS = findViewById(R.id.buttonS);
        buttonD = findViewById(R.id.buttonD);
        buttonL = findViewById(R.id.buttonL);
        // necessário fazer o teste da versão >API 33
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            p = getIntent().getParcelableExtra("dado", Pessoa.class);
        } else {
            p = getIntent().getParcelableExtra("dado");
        }
        if(p!=null){
            editTextNome.setText(p.getNome().toString());
            editTextTelefone.setText(p.getTelefone().toString());
        }
        Banco db = Room.databaseBuilder(getApplicationContext(),
                        Banco.class, "meu_banco")
                .allowMainThreadQueries().build();
        dao = db.pessoaDao();
    }
    public void clicar(View view) {
        if (view.getId() == R.id.buttonS) {
            if (p == null) {
                p = new Pessoa();
                p.setNome(editTextNome.getText().toString());
                p.setTelefone(editTextTelefone.getText().toString());
                long retorno = dao.adicionar(p);
                if (retorno != -1) {
                    Toast.makeText(MainActivity.this, "Salvo", Toast.LENGTH_SHORT).show();
                    p = null;
                    editTextNome.setText("");
                    editTextTelefone.setText("");
                } else {
                    Toast.makeText(MainActivity.this, "Não salvo", Toast.LENGTH_SHORT).show();
                }
            } else {
                p.setNome(editTextNome.getText().toString());
                p.setTelefone(editTextTelefone.getText().toString());
                int retorno = dao.atualizar(p);
                if (retorno != 0) {
                    Toast.makeText(MainActivity.this, "Atualizado", Toast.LENGTH_SHORT).show();
                } else {
                    Toast.makeText(MainActivity.this, "Erro ao atualizar", Toast.LENGTH_SHORT).show();
                }
            }
        }
        if (view.getId() == R.id.buttonL) {
            ArrayList<Pessoa> dados = (ArrayList<Pessoa>) dao.listar();
            if (dados != null && !dados.isEmpty()) {
                Intent intent = new Intent(MainActivity.this, SegundaActivity.class);
                intent.putParcelableArrayListExtra("dados", dados);
                startActivity(intent);
                finish();
            } else {
                Toast.makeText(MainActivity.this, "Sem dados", Toast.LENGTH_SHORT).show();
            }
        }
        if (view.getId() == R.id.buttonD) {
            if (p != null) {
                int retorno = dao.excluir(p);
                if (retorno > 0) {
                    Toast.makeText(MainActivity.this, "Deletado", Toast.LENGTH_SHORT).show();
                    p = null;
                    editTextNome.setText("");
                    editTextTelefone.setText("");
                } else {
                    Toast.makeText(MainActivity.this, "Erro ao deletar", Toast.LENGTH_SHORT).show();
                }
            } else {
                Toast.makeText(MainActivity.this, "Nenhum registro selecionado", Toast.LENGTH_SHORT).show();
            }
        }
    }
}

- SegundaActivity.java
[source,java]
import androidx.appcompat.app.AppCompatActivity;
import android.content.Intent;
import android.os.Build;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import java.util.ArrayList;
public class SegundaActivity extends AppCompatActivity implements AdapterView.OnItemClickListener {
    private ListView listView;
    private ArrayAdapter<Pessoa> adapter;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_segunda);
        listView = findViewById(R.id.lista);
        // necessário fazer o teste da versão >API 33
        ArrayList<Pessoa> dados;
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            dados = getIntent().getParcelableArrayListExtra("dados", Pessoa.class);
        } else {
            dados = getIntent().getParcelableArrayListExtra("dados");
        }
        if (dados == null) dados = new ArrayList<>();
        adapter = new ArrayAdapter<>(this, android.R.layout.simple_list_item_1, dados);
        listView.setAdapter(adapter);
        listView.setOnItemClickListener(this);
    }
    @Override
    public void onItemClick(AdapterView<?> adapterView, View view, int i, long l) {
        Pessoa p = (Pessoa) adapterView.getItemAtPosition(i);
        Intent intent = new Intent(SegundaActivity.this, MainActivity.class);
        intent.putExtra("dado", p); 
        startActivity(intent);
        finish();
    }
}

Versão 2: Esse exemplo é uma adaptação do exemplo disponibilizado em: STACKOVERFLOW. Android Room One-to-Many Relationship. 2021. Disponível: <https://stackoverflow.com/questions/66897173/android-room-one-to-many-relationship>. Pergunta feita pelo usuário <https://stackoverflow.com/users/328518/adil-bhatty> e respondida pelo usuário <https://stackoverflow.com/users/4744514/miket>.












